version: "3.8"

services:
  db:
    image: mysql:8
    container_name: db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: secure_files
    ports:
      - "3306:3306"