# Configurazione Applicazione
spring.application.name=Pirin
file.storage.location=storage

# Connessione al Database MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/secure_files
spring.datasource.username=root
spring.datasource.password=root

# Configurazione JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# DIALETTO AGGIORNATO (Risolve la ClassNotFoundException)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.datasource.url=jdbc:mysql://localhost:3306/secure_files
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=placeholder@gmail.com
spring.mail.password=placeholder
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true